kafka:
  image: spotify/kafka
  ports:
    - "2181:2181"
    - "9092:9092"
  environment:
    ADVERTISED_HOST: localhost
    ADVERTISED_PORT: 9092
    CONSUMER_THREADS: 1
    TOPICS: candlestick-diario, candlestick-semanal
    ZK_CONNECT: kafka7zookeeper:2181/root/path
    GROUP_ID: bmf
    NUM_PARTITIONS: 100
    KAFKA_PRODUCER_MAX_REQUEST_SIZE: 15728640
    KAFKA_CONSUMER_MAX_REQUEST_SIZE: 15728640
    KAFKA_SERVER_MAX_REQUEST_SIZE: 15728640
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

pg-dbbmf:
  image: postgres:10.6-alpine
  environment:
    POSTGRES_DB: dbbmf
    POSTGRES_USER: dbbmf
    POSTGRES_PASSWORD: dbbmf
  volumes:
    - /data/sql/dbbmf:/var/lib/postgresql/data
  ports:
    - "5432:5432"

pg-calcula-dbbmf:
  image: postgres:10.6-alpine
  environment:
    POSTGRES_DB: calcula_bmf
    POSTGRES_USER: dbbmf
    POSTGRES_PASSWORD: dbbmf
  volumes:
    - /data/sql/calcula_bmf:/var/lib/postgresql/data
  ports:
    - "5433:5432"
