-- DROP TABLE HEADER_ARQ;
CREATE TABLE IF NOT EXISTS HEADER_ARQ (
  IDENTIFICACAO_REG BIGINT NOT NULL,
	CODIGO_ORIGEM VARCHAR(50) NULL,
	DATA_GERACAO_ARQUIVO DATE,
	NOME_ARQUIVO VARCHAR(255),
	TIPO_REGISTRO VARCHAR(50) NULL
);

ALTER TABLE HEADER_ARQ ADD PRIMARY KEY (DATA_GERACAO_ARQUIVO, NOME_ARQUIVO);

CREATE SEQUENCE ARQUIVO_SEQ START 1;