server:
  port: 8666

#Swagger
swagger:
  enabled: true

management:
  context-path: /

# Spring properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbbmf
    username: dbbmf
    password: dbbmf
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local
  application:
    name: carga-bmf-arquivo-cotacoes
  main:
    allow-bean-definition-overriding: true
  flyway:
    url: ${spring.datasource.url}
    enabled: true
    checkLocation: false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: false
    schemas: 'public'
  jackson:
    serialization:
      write-dates-as-timestamps: false