server:
  port: 8666

#Swagger
swagger:
  enabled: true

management:
  context-path: /

# Spring properties
spring:
  datasource:
    url: jdbc:postgresql://ec2-34-200-72-77.compute-1.amazonaws.com:5432/d66tth4v85pn22
    username: qzohotthgcajgz
    password: d3ef63c60888c114551ba3126c81c3a80e9d5811083ccd3f0a1d77e775bc34bd
    driver-class-name: org.postgresql.Driver
  profiles:
    active: local
  application:
    name: carga-bmf-arquivo-cotacoes
  flyway:
    url: ${spring.datasource.url}
    enabled: true
    checkLocation: false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: false
    schemas: 'public'
  jackson:
    serialization:
      write-dates-as-timestamps: false