-- DROP TABLE CANDLESTICK_SEMANAL;
CREATE TABLE CANDLESTICK_SEMANAL (
	ID_CANDLE_SEMANAL BIGINT NOT NULL PRIMARY KEY,
	CODNEG VARCHAR(255) NULL,
	DTPREGFIM DATE NULL,
	DTPREGINI DATE NULL,
	PREABE DECIMAL(14,2) NULL,
	PREMAX DECIMAL(14,2) NULL,
	PREMIN DECIMAL(14,2) NULL,
	PREULT DECIMAL(14,2) NULL,
	SEMANA INTEGER NULL,
	VOLTOT DECIMAL(20,2) NULL
);
