-- DROP TABLE COTACAO;
CREATE TABLE COTACAO (
  IDENTIFICACAO_REG BIGINT,
  TPOREG BIGINT NULL,
  DTPREG DATE NULL,
	CODBDI VARCHAR(255) NULL,
	CODNEG VARCHAR(255) NULL,
	TPMERC BIGINT NULL,
	NOMRES VARCHAR(255) NULL,
	ESPECI VARCHAR(255) NULL,
	PRAZOT VARCHAR(255) NULL,
	MODREF VARCHAR(255) NULL,
	PREABE DECIMAL(14,2) NULL,
	PREMAX DECIMAL(14,2) NULL,
	PREMIN DECIMAL(14,2) NULL,
	PREMED DECIMAL(14,2) NULL,
	PREULT DECIMAL(14,2) NULL,
	PREOFC DECIMAL(14,2) NULL,
	PREOFV DECIMAL(14,2) NULL,
	TOTNEG BIGINT NULL,
	QUATOT BIGINT NULL,
	VOLTOT DECIMAL(20,2) NULL,
	PREEXE DECIMAL(14,2) NULL,
	INDOPC BIGINT NULL,
	DATVEN DATE NULL,
	FATCOT BIGINT NULL,
	PTOEXE DECIMAL(14,2) NULL,
	CODISI VARCHAR(255) NULL,
	DISMES BIGINT NULL
);

ALTER TABLE COTACAO ADD PRIMARY KEY (CODNEG, DTPREG, IDENTIFICACAO_REG);