-- DROP TABLE HEADER_ARQ;
CREATE TABLE HEADER_ARQ (
  IDENTIFICACAO_REG BIGINT,
	CODIGO_ORIGEM VARCHAR(50) NULL,
	DATA_GERACAO_ARQUIVO DATE,
	NOME_ARQUIVO VARCHAR(255),
	TIPO_REGISTRO VARCHAR(50) NULL
);

ALTER TABLE HEADER_ARQ ADD PRIMARY KEY (IDENTIFICACAO_REG);

CREATE SEQUENCE ARQUIVO_SEQ START 1;