-- DROP TABLE COTACAO;
CREATE TABLE COTACAO (
	"CODBDI" VARCHAR(255) NULL,
	"CODISI" VARCHAR(255) NULL,
	"CODNEG" VARCHAR(255) NULL,
	"DATVEN" VARCHAR(255) NULL,
	"DISMES" VARCHAR(255) NULL,
	"DTPREG" VARCHAR(255) NULL,
	"ESPECI" VARCHAR(255) NULL,
	"FATCOT" VARCHAR(255) NULL,
	"INDOPC" VARCHAR(255) NULL,
	"MODREF" VARCHAR(255) NULL,
	"NOMRES" VARCHAR(255) NULL,
	"PRAZOT" VARCHAR(255) NULL,
	"PREABE" VARCHAR(255) NULL,
	"PREEXE" VARCHAR(255) NULL,
	"PREMAX" VARCHAR(255) NULL,
	"PREMED" VARCHAR(255) NULL,
	"PREMIN" VARCHAR(255) NULL,
	"PREOFC" VARCHAR(255) NULL,
	"PREOFV" VARCHAR(255) NULL,
	"PREULT" VARCHAR(255) NULL,
	"PTOEXE" VARCHAR(255) NULL,
	"QUATOT" VARCHAR(255) NULL,
	"TPOREG" VARCHAR(255) NULL,
	"TOTNEG" VARCHAR(255) NULL,
	"TPMERC" VARCHAR(255) NULL,
	"VOLTOT" VARCHAR(255) NULL
);

ALTER TABLE COTACAO ADD PRIMARY KEY (CODNEG, DTPREG);