-- DROP TABLE CANDLESTICK_DIARIO;
CREATE TABLE CANDLESTICK_DIARIO (
	ID_CANDLE_DIARIO BIGINT NOT NULL PRIMARY KEY,
	CODNEG VARCHAR(255) NULL,
	DTPREG DATE NULL,
	MEDIA_MOVEL_GERADA BOOLEAN NULL,
	PREABE DECIMAL(14,2) NULL,
	PREMAX DECIMAL(14,2) NULL,
	PREMIN DECIMAL(14,2) NULL,
	PREULT DECIMAL(14,2) NULL,
	SEMANA BIGINT NULL,
	SEMANA_GERADA BOOLEAN NULL,
	VOLTOT DECIMAL(20,2) NULL
);

CREATE SEQUENCE CANDLESTICK_SEQ START 1;
