apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pg-calcula-dbbmf
  name: pg-calcula-dbbmf
spec:
  ports:
  - name: "5433"
    port: 5433
    targetPort: 5432
  selector:
    io.kompose.service: pg-calcula-dbbmf
status:
  loadBalancer: {}
