-- DROP TABLE EMPRESA_SUB_SETOR;
CREATE TABLE IF NOT EXISTS EMPRESA_SUB_SETOR (
	ID_EMPRESA BIGINT NOT NULL,
	ID_SUB_SETOR BIGINT NOT NULL
);

ALTER TABLE EMPRESA_SUB_SETOR ADD PRIMARY KEY (ID_EMPRESA, ID_SUB_SETOR);

ALTER TABLE EMPRESA_SUB_SETOR ADD CONSTRAINT FK_EMPRESA_SUB_SETOR
    FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA (ID_EMPRESA);

ALTER TABLE EMPRESA_SUB_SETOR ADD CONSTRAINT FK_SUB_SETOR_EMPRESA
        FOREIGN KEY (ID_SUB_SETOR)
        REFERENCES SUB_SETOR (ID_SUB_SETOR);
