-- DROP TABLE SUB_SETOR;
CREATE TABLE IF NOT EXISTS SUB_SETOR (
	ID_SUB_SETOR BIGINT NOT NULL,
	DESCRICAO VARCHAR(255) NULL
);

ALTER TABLE SUB_SETOR ADD PRIMARY KEY (ID_SUB_SETOR);

CREATE UNIQUE INDEX ON SUB_SETOR (DESCRICAO);

CREATE SEQUENCE SUB_SETOR_SEQ	START 45;

INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(1, 'Petróleo, Gás e Biocombustíveis');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(2, 'Mineração');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(3, 'Siderurgia e Metalurgia');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(4, 'Químicos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(5, 'Madeira e Papel');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(6, 'Embalagens');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(7, 'Materiais Diversos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(8, 'Construção e Engenharia');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(9, 'Material de Transporte');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(10, 'Máquinas e Equipamentos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(11, 'Transporte');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(12, 'Serviços Diversos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(13, 'Comércio');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(14, 'Agropecuária');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(15, 'Alimentos Processados');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(16, 'Bebidas');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(17, 'Produtos de Uso Pessoal e de Limpeza');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(18, 'Comércio e Distribuição');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(19, 'Construção Civil');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(20, 'Tecidos, Vestuário e Calçados');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(21, 'Utilidades Domésticas');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(22, 'Automóveis e Motocicletas');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(23, 'Hoteis e Restaurantes');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(24, 'Viagens e Lazer');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(25, 'Diversos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(26, 'Medicamentos e Outros Produtos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(27, 'Serviços Médico - Hospitalares');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(28, 'Análises e Diagnósticos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(29, 'Equipamentos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(30, 'Computadores e Equipamentos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(31, 'Programas e Serviços');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(32, 'Telecomunicações');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(33, 'Mídia');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(34, 'Energia Elétrica');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(35, 'Água e Saneamento');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(36, 'Gás');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(37, 'Intermediários Financeiros');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(38, 'Securitizadoras de Recebíveis');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(39, 'Serviços Financeiros Diversos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(40, 'Previdência e Seguros');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(41, 'Exploração de Imóveis');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(42, 'Holdings Diversificadas');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(43, 'Outros Títulos');
INSERT INTO SUB_SETOR(ID_SUB_SETOR, DESCRICAO) VALUES(44, 'Outros');