DELETE FROM SETOR;

INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(1, 'Petróleo, Gás e Biocombustíveis');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(2, 'Materiais Básicos');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(3, 'Bens Industriais');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(4, 'Consumo não Cíclico');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(5, 'Consumo Cíclico');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(6, 'Saúde');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(7, 'Tecnologia da Informação');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(8, 'Comunicações');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(9, 'Utilidade Pública');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(10, 'Financeiro');
INSERT INTO SETOR(ID_SETOR, DESCRICAO) VALUES(11, 'Outros');
