-- DROP TABLE EMPRESA_SEGMENTO;
CREATE TABLE IF NOT EXISTS EMPRESA_SEGMENTO (
	ID_EMPRESA BIGINT NOT NULL,
	ID_SEGMENTO BIGINT NOT NULL
);

ALTER TABLE EMPRESA_SEGMENTO ADD PRIMARY KEY (ID_EMPRESA, ID_SEGMENTO);

ALTER TABLE EMPRESA_SEGMENTO ADD CONSTRAINT FK_EMPRESA_SEGMENTO
    FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA (ID_EMPRESA);

ALTER TABLE EMPRESA_SEGMENTO ADD CONSTRAINT FK_SEGMENTO_EMPRESA
        FOREIGN KEY (ID_SEGMENTO)
        REFERENCES SEGMENTO (ID_SEGMENTO);
