ALTER TABLE EMPRESA ADD COLUMN ID_SETOR BIGINT NULL;
ALTER TABLE EMPRESA ADD COLUMN ID_SUB_SETOR BIGINT NULL;
ALTER TABLE EMPRESA ADD COLUMN ID_SEGMENTO BIGINT NULL;

ALTER TABLE EMPRESA
ADD CONSTRAINT FK_EMPRESA_SETOR
FOREIGN KEY (ID_SETOR) REFERENCES SETOR (ID_SETOR);

ALTER TABLE EMPRESA
ADD CONSTRAINT FK_EMPRESA_SUB_SETOR
FOREIGN KEY (ID_SUB_SETOR) REFERENCES SUB_SETOR (ID_SUB_SETOR);

ALTER TABLE EMPRESA
ADD CONSTRAINT FK_EMPRESA_SEGMENTO
FOREIGN KEY (ID_SEGMENTO) REFERENCES SEGMENTO (ID_SEGMENTO);
