-- DROP TABLE CALENDARIO_FERIADO;
CREATE TABLE IF NOT EXISTS CALENDARIO_FERIADO (
	ID_CALENDARIO BIGINT NOT NULL,
	DATA_CALENDARIO DATE NOT NULL,
	DIA_SEMANA VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(255) NULL
);

ALTER TABLE CALENDARIO_FERIADO ADD PRIMARY KEY (DATA_CALENDARIO);

CREATE SEQUENCE CALENDARIO_FERIADO_SEQ	START 1;


INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(1, '2020-01-01', 'quarta-feira', 'Confraternização Universal');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(2, '2020-02-24', 'segunda-feira', 'Carnaval');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(3, '2020-02-25', 'terça-feira', 'Carnaval');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(4, '2020-04-10', 'sexta-feira', 'Paixão de Cristo');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(5, '2020-04-21', 'terça-feira', 'Tiradentes');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(6, '2020-05-01', 'sexta-feira', 'Dia do Trabalho');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(7, '2020-06-11', 'quinta-feira', 'Corpus Christi');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(8, '2020-07-09', 'quinta-feira', 'Revolução Constitucionalista');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(9, '2020-09-07', 'segunda-feira', 'Dia da Independência do Brasil');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(10, '2020-10-12', 'segunda-feira', 'Nossa Senhora Aparecida Padroeira do Brasil');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(11, '2020-11-02', 'segunda-feira', 'Finados');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(12, '2020-11-20', 'sexta-feira', 'Consciência Negra');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(13, '2020-12-24', 'quinta-feira', 'Véspera de Natal');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(14, '2020-12-25', 'sexta-feira', 'Natal');

INSERT INTO CALENDARIO_FERIADO(ID_CALENDARIO, DATA_CALENDARIO, DIA_SEMANA, DESCRICAO)
VALUES(15, '2020-12-31', 'quinta-feira', 'Expediente interno nas instituições bancárias (sem sessão de negociação na B3)');