server:
  port: 8666
# Spring properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbbmf
    username: dbbmf
    password: dbbmf
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    enabled: true
    checkLocation: false
    locations: db/migrations
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baselineOnMigrate: true
    versions: 1
  profiles:
    active: local
  application:
    name: carga-bmf-arquivo-cotacoes
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_bmf